In [20]:
#Работа с NumPy

### Создание массивов из обычных списков

import numpy as np

# Одномерный массив из списка
arr = np.array([1, 2 , 3, 4])
print("Одномерный массив из списка: ", arr)

#Двумерный массив
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Двумерный массив: ", arr2)

# Массив с разынми типами данных
arr_float = np.array([1.5, 2.7, 3.1])
print("Массив с разынми типами данных: ", arr_float)

### Создание массивов с помощью функций zeros, ones, arange
# Массив нулей
arr_zeros = np.zeros((3, 3))
print("Массив нулей:\n", arr_zeros)

# Массив единиц
arr_ones = np.ones((2, 4))
print("Массив единиц:\n", arr_ones)

# Массив с arange(с последовательностью чисел)
range_arr = np.arange(0, 10, 2)  #шаг 2
print("Массив с arange(0, 10, 2): ", range_arr)

# Массив с линейным пространством
linspace_arr = np.linspace(0, 1, 5)  # 5 чисел от 0 до 1
print("Массив с linspace(0, 1, 5):", linspace_arr)

# Единичная матрица
identity_matrix = np.eye(3)
print("\nЕдиничная матрица 3x3:")
print(identity_matrix)

### Демонстрация атрибутов shape и dtype

test_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Форма:", test_array.shape)
print("dtype (тип данных):", test_array.dtype)
print("ndim (размерность):", test_array.ndim)
print("size (количество элементов):", test_array.size)

### Индексирование - получение отдельных элементов
arr_demo = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Элемент [0, 0]:", arr_demo[0, 0])
print("Элемент [2,1]:", arr_demo[2, 1])
print("Элемент [-1,-1]:", arr_demo[-1, -1])  # Последний элемент

# Индексирование для одномерного массива
arr_1d = np.array([5, 10, 15, 20])
print("\nОдномерный массив:", arr_1d)
print("Первый элемент:", arr_1d[0])
print("Последний элемент:", arr_1d[-1])


### Срезы - извлечение подмассивов
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print("Исходный массив:")
print(arr)

print("\n--- Срезы ---")
print("Первые две строки:")
print(arr[0:2, :])  # Все столбцы, первые две строки
print("\nПоследние два столбца:")
print(arr[:, 2:])

# Срезы в одномерном массиве
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("\nОдномерный массив:", arr_1d)
print("Срез [2:7]:", arr_1d[2:7]) 

### Базовые статистики
data = np.array([23, 45, 12, 67, 89, 34, 56, 78, 91, 15])

print("Данные:", data)

print("\n--- Базовые статистики ---")
print("Среднее значение (mean):", np.mean(data))

### Поэлементные операции с массивами
print("=== ПОЭЛЕМЕНТНЫЕ ОПЕРАЦИИ ===")

# Создаем два массива одинаковой формы
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Массив a:", a)
print("Массив b:", b)

print("\n--- Поэлементное сложение ---")
result_add = a + b
print("Сумма а и b: ", result_add)

Одномерный массив из списка:  [1 2 3 4]
Двумерный массив:  [[1 2 3]
 [4 5 6]]
Массив с разынми типами данных:  [1.5 2.7 3.1]
Массив нулей:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Массив единиц:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Массив с arange(0, 10, 2):  [0 2 4 6 8]
Массив с linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

Единичная матрица 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Форма: (3, 4)
dtype (тип данных): int64
ndim (размерность): 2
size (количество элементов): 12
Элемент [0, 0]: 10
Элемент [2,1]: 80
Элемент [-1,-1]: 90

Одномерный массив: [ 5 10 15 20]
Первый элемент: 5
Последний элемент: 20
Исходный массив:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

--- Срезы ---
Первые две строки:
[[1 2 3 4]
 [5 6 7 8]]

Последние два столбца:
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Одномерный массив: [0 1 2 3 4 5 6 7 8 9]
Срез [2:7]: [2 3 4 5 6]
Данные: [23 45 12 67 89 34 56 78 91 15]

--- Базовые статистики ---
Среднее значение (mean): 51.0
=== ПОЭЛЕМЕНТНЫЕ ОПЕРАЦИИ ===
Масси